<?php include_once BP . '/view/layout/header.phtml' ?>

<div class="row">
    <div class="container">
        <h1>Paydesk</h1>
        <hr>
        <form action="/~polaznik22/paydesk" method="post" class="form-inline my-2 my-lg-0">
            <input type="search" name="searchItem" id="search" class="form-control mr-sm-2 ml-2">
        </form>

        <?php
        if(!empty($products)): ?>
        <table class="table mt-2">
           <thead>
                <th>Title</th><th>Author</th><th>Condition</th><th>Price</th><th>Action</th>
           </thead>

            <?php foreach ($products as $product):
                    if ($product->getAmount() > 0):
            ?>
           <tbody>
                <tr>
                    <td>
                        <p><?=$product->getTitle()?></p>
                        <small><?=$product->getSubtitle()?></small>
                    </td>
                    <td><?=$product->getAuthor()?></td>
                    <td><?=$product->getconditions()?></td>
                    <td><?=$product->sellPrice?></td>
                    <td>
                        <form method="post" action="/~polaznik22/paydesk/cart">
                            <input type="hidden" name="productId" value="<?= $product->getId() ?>">
                            <input type="hidden" name="condition" value="<?= $product->conditionId ?>">
                            <button>Add</button>
                        </form>
                    </td>
                </tr>
           </tbody>
            <?php
                    endif;
                endforeach;
            ?>
         </table>
        <?php endif; ?>
    </div>
</div>
<hr>
<div class="row">
    <div class="container">
        <?php if(!empty($paydesk)): ?>
       <table class="table table-striped">
           <thead>
                <th>Title</th><th>Author</th><th>Condition</th><th>Price</th><th>Action</th>
           </thead>
           <tbody>
           <?php foreach ($paydesk as $item): ?>
                <tr>
                    <td>
                        <h5><?= $item->getTitle() ?></h5>
                        <small><?= $item->getSubtitle() ?></small>
                    </td>
                    <td><p><?= $item->getAuthor() ?></p></td>
                    <td><p><?= $item->conditions ?></p></td>
                    <td><p align="right"><?= $item->sellPrice ?>kn</p></td>
                    <td><form action="/~polaznik22/paydesk/remove" method="post">
                            <input type="hidden" name="itemId" value="<?= $item->getId() ?>">
                            <button>X</button>
                        </form>
                    </td>
                </tr>
            <?php endforeach; ?>
                <tr>
                    <th colspan="3"> Total</th>
                    <td align="right"><?= isset($total) ? $total : '' ?>kn</td>
                    <td></td>
                </tr>
           </tbody>
       </table>

        <div>
            <form action="/~polaznik22/paydesk/process" method="post">
                <input type="hidden" name="total" value="<?= $total ?>">
                <button>Process</button>
            </form>
        </div>
        <?php endif; ?>
    </div>
</div>

<?php include_once BP . '/view/layout/footer.phtml' ?>