<?php include_once BP . '/view/layout/header.phtml' ?>

<div class="row">
    <div class="container">
        <h1 class="text-center mb-5">Antikvarijat</h1>
        <input type="search"> <button type="submit" >Search</button>
        <table class="table table-striped">
            <thead>
            <th>Title</th>
            <th>Author</th>
            <th>Publisher</th>
            <th>Cover</th>
            <th>Amount</th>
            <th>Sell Price</th>
            <th>Buy Price</th>
            <th>Action</th>
            </thead>

            <tbody>
                <tr>
                    <td>Hichhiker's guide to the galaxy - first book</td>
                    <td>William Gibson</td>
                    <td>PB</td>
                    <td>s</td>
                    <td align="center">3</td>
                    <td>79kn</td>
                    <td>35kn</td>
                    <td>edit  delete</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<?php include_once BP . '/view/layout/footer.phtml' ?>
