<?php include_once BP . '/view/layout/header.phtml' ?>

    <div class="row">
        <div class="container">
            <h1>Acquisitions</h1>
            <hr>
            <form action="/~polaznik22/acquisition/create" method="post" class="form-inline my-2 my-lg-0">
                <input type="search" name="searchItem" id="search" class="form-control mr-sm-2 ml-2">
            </form>

            <?php
            if(!empty($products)): ?>
                <table class="table mt-2">
                    <thead>
                    <th>Title</th><th>Author</th><th>Condition</th><th>Amount</th><th>Price</th><th>Action</th>
                    </thead>

                    <?php foreach ($products as $product): ?>
                            <tbody>
                            <tr>
                                <td>
                                    <p><?=$product->getTitle()?></p>
                                    <small><?=$product->getSubtitle()?></small>
                                </td>
                                <td><?=$product->getAuthor()?></td>
                                <td><?=$product->getconditions()?></td>
                                <td><?=$product->getAmount()?></td>
                                <td><?=$product->buyPrice ?></td>
                                <td>
                                    <form method="post" action="/~polaznik22/acquisition/cart">
                                        <input type="hidden" name="productId" value="<?= $product->getId() ?>">
                                        <input type="hidden" name="condition" value="<?= $product->conditionId ?>">
                                        <button class="btn btn-primary"><i class="far fa-plus-square"></i></button>
                                    </form>
                                </td>
                            </tr>
                            </tbody>
                        <?php endforeach; ?>
                </table>
            <?php endif; ?>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="container">
            <?php if(!empty($productInCart)): ?>
                <table class="table table-striped">
                    <thead>
                    <th>Title</th><th>Author</th><th>Condition</th><th>Price</th><th>Action</th>
                    </thead>
                    <tbody>
                    <?php foreach ($productInCart as $item): ?>
                        <tr>
                            <td>
                                <h5><?= $item->title ?></h5>
                                <small><?= $item->subtitle ?></small>
                            </td>
                            <td><p><?= $item->author ?></p></td>
                            <td><p><?= $item->conditions ?></p></td>
                            <td><p align="right"><?= $item->buyPrice ?>kn</p></td>
                            <td><form action="/~polaznik22/acquisition/remove" method="post">
                                    <input type="hidden" name="itemId" value="<?= $item->id ?>">
                                    <input type="hidden" name="conditionId" value="<?= $item->conditionId ?>">
                                    <button class="btn btn-danger"><i class="fas fa-times"></i></button>
                                </form>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    <tr>
                        <th colspan="3"> Total</th>
                        <td align="right"><?= isset($total) ? $total : '' ?>kn</td>
                        <td></td>
                    </tr>
                    </tbody>
                </table>

                <div>
                    <form action="/~polaznik22/acquisition/process" method="post">
                        <input type="hidden" name="total" value="<?= $total ?>">
                        <button class="btn btn-primary">Process</button>
                    </form>
                </div>
            <?php endif; ?>
        </div>
    </div>

<?php include_once BP . '/view/layout/footer.phtml' ?>