<?php include_once BP . '/view/layout/header.phtml' ?>

<div class="row">
    <div class="container">

        <table class="table table-striped">
            <thead><th>Title</th><th>Condition</th><th>In Stock</th><th>Buy Price</th><th>Sell Price</th><th>Receipt#</th></thead>

            <tbody>
            <?php
            $total = 0;

            foreach ($products as $product):
                $total += $product->sellPrice;
            ?>
                <tr>
                    <td>
                        <h5><?= $product->title ?></h5>
                        <small><?= $product->subtitle ?></small>
                        <p><?= $product->author ?></p>
                    </td>
                    <td><?= $product->conditions ?></td>
                    <td align="center"><?= $product->amount ?></td>
                    <td align="center"><?= $product->buyPrice ?>kn</td>
                    <td align="center"><?= $product->sellPrice ?>kn</td>
                    <td><?= $product->receipt ?></td>
                </tr>

            <?php endforeach ?>
                <tr><th colspan="4">Total</th><td align="center"><b><?= $total ?>kn</b></td><td></td></tr>
            </tbody>
        </table>
        <a href="/~polaznik22/acquisition" class="btn btn-danger">Back</a>

    </div>
</div>

<?php include_once BP . '/view/layout/footer.phtml' ?>