<?php include_once BP . '/view/layout/header.phtml' ?>

<div class="row">
    <div class="container">

        <table class="table table-striped">
            <thead><th>Title</th><th>Author</th><th>Buy Price</th><th>Sell Price</th><th>Condition</th></thead>

            <tbody>
            <?php foreach ($products as $product): ?>
                <tr>
                    <td>
                        <p><?= $product->title ?></p>
                        <small><?= $product->subtitle ?></small>
                    </td>
                    <td><?= $product->author ?></td>
                    <td><?= $product->buyPrice ?></td>
                    <td><?= $product->sellPrice ?></td>
                    <td><?= $product->conditions ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <a href="/~polaznik22/acquisition" class="btn btn-danger">Back</a>
    </div>
</div>

<?php include_once BP . '/view/layout/footer.phtml' ?>