<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/~polaznik22/">Antikvarijat</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <?php if (!\App\Core\Session::getInstance()->isLoggedIn()): ?>
            <li class="nav-item active">
                <a class="nav-link" href="/~polaznik22/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/~polaznik22/login">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/~polaznik22/register">Register</a>
            </li>
            <?php elseif(\App\Core\Session::getInstance()->getUser()->getAdmin()): ?>
            <li class="nav-item active">
                <a class="nav-link" href="/~polaznik22/product">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Aquisitions</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/~polaznik22/paydesk">Cash register</a>
            </li>
            <?php else: ?>
                <li class="nav-item">
                    <a class="nav-link" href="/~polaznik22/">Home</a>
                </li>
            <?php endif ?>
        </ul>

        <!-- Right Side Of Navbar -->
        <ul class="navbar-nav ml-auto">
            <?php if(\App\Core\Session::getInstance()->isLoggedIn()): ?>
            <li class="nav-item dropdown">
                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                    <span class="caret"><?= \App\Core\Session::getInstance()->getUser()->getUsername() ?></span>
                </a>

                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <?php if(\App\Core\Session::getInstance()->getUser()->getAdmin() == 1): ?>
                    <a class="dropdown-item" href="/~polaznik22/product/create">Add Product</a>
                    <div class="dropdown-divider"></div>
                    <?php endif ?>
                    <a class="dropdown-item" href="/~polaznik22/logout">logout</a>
                </div>
            </li>
            <?php endif  ?>
        </ul>
    </div>
</nav>