<?php include_once 'layout/header.phtml' ?>

    <div class="row">
        <div class="container">
            <h1 class="text-center mb-5">Antikvarijat</h1>
            <table class="table table-striped">
                <thead>
                    <th>Title</th>
                    <th>Author</th>
                    <th>Price</th>
                    <th>Action</th>
                </thead>
                <tbody>
                <?php foreach ($products as $product): ?>
                    <tr>
                        <td>
                            <a href="show?id=<?= $product->getId() ?>"><?= $product->getTitle();  ?></a>
                            <small><?= $product->getSubtitle() ? ' - ' . $product->getSubtitle() : '' ; ?></small>
                        </td>
                        <td><?= $product->getAuthor()  ?></td>
                        <td><?= $product->getRetail_price() . 'kn'  ?></td>
                        <td><a href="">Buy</a></td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>

        </div>
    </div>



<?php include_once 'layout/footer.phtml' ?>
