<?php include_once 'layout/header.phtml' ?>

<div class="row">
    <div class="container">
        <h1 class="text-center mb-5">Antikvarijat</h1>
        <form action="search" method="post">
            <input type="search" name="search"> <button type="submit" >Search</button>
        </form>
        <table class="table table-striped">
            <thead>
            <th>Image</th>
            <th>Title</th>
            <th>Author</th>
            <th>Publisher</th>
            <th>Category</th>
            <th>Format</th>
            <th>Condition</th>
            <th>Price</th>
            <th>Action</th>
            </thead>

            <tbody>
            <?php
            foreach ($products as $product):
                if($product->amount > 0):
            ?>
                <tr>
                    <td>
                        <img src="<?= $product->image  ?>" alt="cover" />
                    <td>
                        <h6><a href="/~polaznik22/product/show?id=<?=$product->id ?>"><?= $product->title ?></a></h6>
                        <small><?= $product->subtitle ?></small>
                    </td>
                    <td><?= $product->author ?></td>
                    <td>
                        <?= $product->publisher ?>
                        <?= $product->year ? '('.$product->year.')' : ''?>
                    </td>
                    <td>
                        <?= $product->category ?>
                    </td>
                    <td><?= $product->format ?></td>
                    <td><?= $product->conditions ?></td>
                    <td><?= $product->sellPrice ?>kn</td>
                    <td><a href="#">Buy</a></td>
                </tr>
            <?php
                endif;
            endforeach;
            ?>
            </tbody>
        </table>
    </div>
</div>

<?php include_once 'layout/footer.phtml' ?>
