<?php include_once 'layout/header.phtml' ?>

<div class="row">
    <div class="container">
        <h1 class="text-center mb-5">Antikvarijat</h1>
        <div class="col-sm-6 mb-3 offset-2">
            <form action="/~polaznik22/" method="post" class="form-inline my-2 my-lg-0">
                <label for="search">Search:</label>
                <input type="search" name="search" id="search" class="form-control mr-sm-2 ml-2">
                <button type="submit" class="btn btn-primary form-control">Search</button>
            </form>
        </div>
    </div>
</div>
<hr>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="row">
                <?php
                foreach ($products as $product):
                    if($product->amount > 0):
                        ?>
                        <div class="card mr-2  mb-2" style="width: 18rem;">
                            <div class="card-body">
                                <img src="/<?= $product->getImage() ?>" alt="cover" class="image">
                                <h5 class="card-title"><?= $product->getTitle()  ?></h5>
                                <h6 class="card-subtitle mb-2 text-muted"><?= $product->getSubtitle()  ?></h6>
                                <p><?= $product->getAuthor()  ?></p>
                                <br>
                                <p><span class="badge badge-warning"><?= $product->getConditions()  ?></span> Condition</p>
                                <p><small><?= $product->getFormat()  ?></small></p>
                                <p><?= $product->getSellPrice()  ?></p>
                                <p align="right"><a href="#">Cart</a></p>
                            </div>
                        </div>
                    <?php
                    endif;
                endforeach;
                ?>
            </div>
        </div>
    </div>
</div>

<?php include_once 'layout/footer.phtml' ?>
