<?php include_once 'layout/header.phtml' ?>

<div class="container">
    <div class="container">
        <form method="post" action="login">
            <fieldset class="border p-2">
                <legend class="w-auto">Register</legend>
                <div class="form-group">
                    <label for="username">Name:</label>
                    <input type="text" name="username" class="form-control" id="username" aria-describedby="emailHelp" placeholder="Enter a name">
                </div>
                <div class="form-group">
                    <label for="email">Email address:</label>
                    <input type="email" name="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email">
                </div>
                <div class="form-group">
                    <label for="password">Password:</label>
                    <input type="password" name="password" class="form-control" id="password" placeholder="Password">
                </div>

                <button type="submit" class="btn btn-primary btn-block mt-2">Register</button>
            </fieldset>
        </form>
        <p class="mt-5 text-center">Already registered? <a href="login">Login here</a></p>
    </div>
</div>

<?php include_once 'layout/footer.phtml' ?>
